name: Build and Deploy

on:
  push:
    branches:
      - docs

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
        uses: actions/checkout@master

    - name: Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: Leecason/leecason.github.io
        TARGET_BRANCH: master
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: docs/.vuepress/dist/
